### ISSUE TITLE
jQuery scripts inside modal window

### ISSUE THREAD

**Issue by firebull** [vjik/arcticModal#2]
If you create any jQuery script inside modal window, it won't work. 
Script can start initially, but any function like $.click doesn't work.

**Comment by vjik** [comment]
Give example, pls

**Comment by firebull** [comment]
For example, this div:

```
<div class="b-modal" id="modal_container">

    <div class="modal-header">
        <button type="button" class="close" onClick="$.arcticmodal('close');">&times;</button>
        <h3 id="modal_header"></h3>
    </div>

    <script>
    $(function() {
        $( "#tabs" ).tabs();
    });
    </script>

    <div id="tabs">
        <ul>
            <li><a href="#tabs-1">Nunc tincidunt</a></li>
            <li><a href="#tabs-2">Proin dolor</a></li>
            <li><a href="#tabs-3">Aenean lacinia</a></li>
        </ul>
        <div id="tabs-1">
            <p>Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus. Curabitur nec arcu. Donec sollicitudin mi sit amet mauris. </p>
        </div>
        <div id="tabs-2">
            <p>Morbi tincidunt, dui sit amet facilisis feugiat, odio metus gravida ante, ut pharetra massa metus id nunc. </p>
        </div>
        <div id="tabs-3">
            <p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti. Aliquam vulputate, pede vel vehicula accumsan, mi neque rutrum erat, eu congue orci lorem eget lorem. Vestibulum non ante. .</p>           
        </div>
    </div>
</div>
```

**Comment by firebull** [comment]
That example is modal window with jQuery UI Tabs in it.

**Comment by vjik** [comment]
use **class** instead of **id** and init your functions on **afterOpen** event
arcticmodal use **clone** (https://github.com/vjik/arcticModal/blob/master/arcticmodal/jquery.arcticmodal.js#L137) for show div

**Comment by vjik** [comment]
in future version this behavior be fixed

sorru for my english =)

**Comment by firebull** [comment]
Ok, I'll check it out. Thx.

**Comment by firebull** [comment]
Можно и по-русски =) Это я так, для буржуев =)

**Comment by olegdenisov** [comment]
Я ж в своих коммитах предлагал отказаться от клонирования, разве не приняли. И проблема выше отпадает потом.

**Comment by vjik** [comment]
да, поправим это скоро

**Comment by vjik** [comment]
Добавил опцию clone.
Если включена - то будет работать как раньше с клонированием. Если отключить - будет работать без клонирования.
По-умолчанию false
