### ISSUE TITLE
Баг: очередность закрытия окон

### ISSUE THREAD

**Issue by wackyfrog** [vjik/arcticModal#6]
&#x043e;&#x043a;&#x043d;&#x0430; &#x0437;&#x0430;&#x043a;&#x0440;&#x044b;&#x0432;&#x0430;&#x044e;&#x0442;&#x0441;&#x044f; &#x043f;&#x043e; escape &#x043d;&#x0435; &#x0432; &#x0442;&#x043e;&#x0439; &#x043f;&#x043e;&#x0441;&#x043b;&#x0435;&#x0434;&#x043e;&#x0432;&#x0430;&#x0442;&#x0435;&#x043b;&#x044c;&#x043d;&#x043e;&#x0441;&#x0442;&#x0438;<br/><br/>&#x0441;&#x0442;&#x0440;&#x043e;&#x043a;&#x0430; 156 (&#x0434;&#x043e;&#x0431;&#x0430;&#x0432;&#x0438;&#x043b; log):<br/>            // &#x0417;&#x0430;&#x043f;&#x043e;&#x043c;&#x043d;&#x0438;&#x043c; &#x043d;&#x0430;&#x0441;&#x0442;&#x0440;&#x043e;&#x0439;&#x043a;&#x0438;<br/>           $this.data('arcticmodal', D);<br/>console.log(&quot;before&quot;, modals);<br/>         modals = modals.add($this);<br/>console.log(modals);<br/><br/>&#x0438; &#x0432;&#x043e;&#x0442; &#x043a;&#x0430;&#x043a; &#x043f;&#x043e;&#x043b;&#x0443;&#x0447;&#x0430;&#x0435;&#x0442;&#x0441;&#x044f;:<br/><br/>before [] jquery.arcticmodal.js:158<br/>[&lt;div class=&#x200b;&quot;window&quot; id=&#x200b;&quot;window-purchase&quot;&gt;&#x200b;&#x2026;&#x200b;&lt;/div&gt;&#x200b;] jquery.arcticmodal.js:160<br/><br/>[before [&lt;div class=&#x200b;&quot;window&quot; id=&#x200b;&quot;window-purchase&quot;&gt;&#x200b;&#x2026;&#x200b;&lt;/div&gt;&#x200b;] jquery.arcticmodal.js:158<br/>&lt;div class=&#x200b;&quot;window&quot;&gt;&#x200b;&#x2026;&#x200b;&lt;/div&gt;&#x200b;,  &lt;div class=&#x200b;&quot;window&quot; id=&#x200b;&quot;window-purchase&quot;&gt;&#x200b;&#x2026;&#x200b;&lt;/div&gt;&#x200b;<br/>] jquery.arcticmodal.js:160<br/><br/>before [&lt;div class=&#x200b;&quot;window&quot;&gt;&#x200b;&#x2026;&#x200b;&lt;/div&gt;&#x200b;, &lt;div class=&#x200b;&quot;window&quot; id=&#x200b;&quot;window-purchase&quot;&gt;&#x200b;&#x2026;&#x200b;&lt;/div&gt;&#x200b;] jquery.arcticmodal.js:158<br/><br/>[&lt;div class=&#x200b;&quot;window&quot;&gt;&#x200b;&#x2026;&#x200b;&lt;/div&gt;&#x200b;, &lt;div class=&#x200b;&quot;window&quot; id=&#x200b;&quot;window-purchase&quot;&gt;&#x200b;&#x2026;&#x200b;&lt;/div&gt;&#x200b;, &lt;div class=&#x200b;&quot;window&quot;&gt;&#x200b;&#x2026;&#x200b;&lt;/div&gt;&#x200b;] jquery.arcticmodal.js:160<br/>

**Comment by vjik** [comment]
Исправил в dev-ветке.
Почему-то $.add иногда добавлял в начало массива окна (хотя должен в конец).
